export type Product = {
  id: number | string;
  slug: string;
  name: string;
  description: string;
  price: number | null;
  priceDisplay: string;
  category: string;
  image: string;
  images?: string[];
  inStock: boolean;
  featured?: boolean;
  averageRating?: number;
  reviewCount?: number;
};

export const products: Product[] = [
  {
    id: 1,
    slug: "vegetable-cutter",
    name: "Multi-function Chopping Vegetable Cutter",
    description: "Multi-function Chopping Vegetable Cutter Device Cut Dice/Wire/Slices. Saves time in the kitchen with multiple cutting options.",
    price: null,
    priceDisplay: "Contact for price",
    category: "Kitchen",
    image: "/products/product-1.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: 2,
    slug: "toilet-paper-holder",
    name: "Extra Large Toilet Paper Basket Holder",
    description: "SpaceAid Extra Large Toilet Paper Storage with Lid. Holds up to 24 Regular Rolls or 18 Mega Rolls. Slim design fits any bathroom.",
    price: null,
    priceDisplay: "Contact for price",
    category: "Bathroom",
    image: "/products/product-2.jpg",
    inStock: true,
  },
  {
    id: 3,
    slug: "double-pole-clothes-rack",
    name: "Double Pole Telescopic Clothes Rack",
    description: "Versatile and adjustable double pole telescopic clothes rack. Made of stainless steel and durable plastic. Perfect for indoor storage and drying laundry.",
    price: 35000,
    priceDisplay: "35,000 RWF",
    category: "Home",
    image: "/products/product-3.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: 4,
    slug: "mini-steppers",
    name: "Mini Steppers For Exercise",
    description: "Mini Steppers For Exercise with Twist Stair Stepper and Resistance Bands. Full Body Workout At Home. LCD monitor tracks steps, time, and calories. 120kg capacity.",
    price: 120000,
    priceDisplay: "120,000 RWF",
    category: "Fitness",
    image: "/products/product-4.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: 5,
    slug: "washing-machine-feet-pad",
    name: "4PCS Washing Machine Feet Pads",
    description: "Rubber Non-Slip Mats for Dryer, Washing Machine, and Dishwasher. Prevents vibration and movement during cycles.",
    price: 18000,
    priceDisplay: "18,000 RWF",
    category: "Home",
    image: "/products/product-5.jpg",
    inStock: true,
  },
  {
    id: 6,
    slug: "movable-base-stand",
    name: "Multifunctional Movable Base Stand",
    description: "Appliance Rollers for Dryer, Refrigerator, Stacked Washer & Dryer Units. Heavy duty and easy to move.",
    price: 50000,
    priceDisplay: "50,000 RWF",
    category: "Home",
    image: "/products/product-6.jpg",
    inStock: true,
  },
  {
    id: 7,
    slug: "clothes-drying-rack",
    name: "Clothes Drying Rack Foldable",
    description: "Foldable Clothes Drying Rack with large capacity. Space saving design, easy to fold and store.",
    price: 65000,
    priceDisplay: "65,000 RWF",
    category: "Home",
    image: "/products/product-7.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: 8,
    slug: "resistance-bands",
    name: "Resistance Band Exercise Straps Set of 5",
    description: "Home Gym Yoga Fitness Accessories. Heavy Duty Elastic Loops Pilates Straps. Perfect for all fitness levels.",
    price: 15000,
    priceDisplay: "15,000 RWF",
    category: "Fitness",
    image: "/products/product-8.jpg",
    inStock: true,
  },
  {
    id: 9,
    slug: "rain-coat",
    name: "Rain Coat (Blue & Green)",
    description: "Quality rain coat available in multiple colors. Blue (Ubururu) and Green (Icyatsi). Perfect for the rainy season.",
    price: 13000,
    priceDisplay: "13,000 – 17,000 RWF",
    category: "Clothing",
    image: "/products/product-9.jpg",
    inStock: true,
  },
  {
    id: 10,
    slug: "shower-caddy-5pack",
    name: "Shower Caddy 5 Pack",
    description: "Adhesive Shower Organizer Bathroom Shelves. Rustproof bathroom storage. No drilling required.",
    price: 50000,
    priceDisplay: "50,000 RWF",
    category: "Bathroom",
    image: "/products/product-10.jpg",
    inStock: true,
  },
  {
    id: 11,
    slug: "laptop-bed-table",
    name: "Adjustable Laptop Bed Table",
    description: "Foldable Desk Table with Cup Holder and Non-Slip Cushion Tray. Perfect for working from bed or sofa.",
    price: 30000,
    priceDisplay: "30,000 RWF",
    category: "Office",
    image: "/products/product-11.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: 13,
    slug: "water-heater-shower",
    name: "Electric Instant Water Heater Shower",
    description: "3-nozzle electric instant water heater for shower. Enjoy hot water whenever you need. Easy to install.",
    price: 135000,
    priceDisplay: "135,000 RWF",
    category: "Bathroom",
    image: "/products/product-13.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: 15,
    slug: "furniture-mover-heavy",
    name: "Furniture Mover Heavy Duty",
    description: "Move heavy furniture easily without scratching floors. Set of movers with handles.",
    price: 40000,
    priceDisplay: "40,000 RWF",
    category: "Home",
    image: "/products/product-15.jpg",
    inStock: true,
  },
  {
    id: 17,
    slug: "blender-8in1",
    name: "Multifunction 8 in 1 Blender",
    description: "Multifunction 8 in 1 Blender for kitchen. Multiple functions in one device. Easy to use and clean.",
    price: 130000,
    priceDisplay: "130,000 RWF",
    category: "Kitchen",
    image: "/products/product-17.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: 18,
    slug: "garden-hose-spray-gun",
    name: "Garden Hose Water Spray Gun 8 Mode",
    description: "Car Wash High Pressure Sprayer. Watering Nozzle for Lawn, Plant, Yard. Available with 10m, 20m, or 30m pipe.",
    price: 25000,
    priceDisplay: "25,000 – 45,000 RWF",
    category: "Garden",
    image: "/products/product-18.jpg",
    inStock: true,
  },
  {
    id: 19,
    slug: "air-fryer",
    name: "Silver Crest Air Fryer 2400W",
    description: "XXL Capacity Air Fryer with Visible Viewing Food Basket. Perfect for 3-6 Persons. 8 Pre-set Functions. 2400W (Black).",
    price: 90000,
    priceDisplay: "90,000 RWF",
    category: "Kitchen",
    image: "/products/product-19.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: 20,
    slug: "toilet-rack-3tray",
    name: "Toilet Rack 3 Trays",
    description: "Space-saving toilet rack with 3 trays. Perfect bathroom organizer for all your toiletries.",
    price: 45000,
    priceDisplay: "45,000 RWF",
    category: "Bathroom",
    image: "/products/product-20.jpg",
    inStock: true,
  },
  {
    id: 21,
    slug: "corner-shower-caddy",
    name: "Corner Shower Caddy 5-Pack",
    description: "Large Capacity Stainless Steel Corner Shower Caddy. Fits perfectly in shower corners. Rustproof design.",
    price: 50000,
    priceDisplay: "50,000 RWF",
    category: "Bathroom",
    image: "/products/product-21.jpg",
    inStock: true,
  },
  {
    id: 22,
    slug: "double-pole-rack-v2",
    name: "Double Pole Telescopic Rack",
    description: "Adjustable double pole telescopic clothes rack. Stainless steel and durable plastic. Great for indoor use.",
    price: 35000,
    priceDisplay: "35,000 RWF",
    category: "Home",
    image: "/products/product-22.jpg",
    inStock: true,
  },
  {
    id: 25,
    slug: "furniture-mover-light",
    name: "Furniture Mover Multifunction",
    description: "Multifunction furniture mover for easy rearranging. Protects floors from scratches.",
    price: 25000,
    priceDisplay: "25,000 RWF",
    category: "Home",
    image: "/products/product-25.jpg",
    inStock: true,
  },
  {
    id: 27,
    slug: "washing-machine-support-mat",
    name: "Washing Machine Anti-Vibration Mat (4pcs)",
    description: "Anti-Vibration Leg Stopper Foot Pad Feet Pads for washing machines. Reduces noise and vibration.",
    price: 18000,
    priceDisplay: "18,000 RWF",
    category: "Home",
    image: "/products/product-27.jpg",
    inStock: true,
  },
  {
    id: 28,
    slug: "bathroom-suction-holder",
    name: "Multifunction Bathroom Suction Holder (Set of 3)",
    description: "Strong suction cup bathroom organizer. No drilling needed. Set of 3 pieces for versatile use.",
    price: 18000,
    priceDisplay: "18,000 RWF",
    category: "Bathroom",
    image: "/products/product-28.jpg",
    inStock: true,
  },
  {
    id: 29,
    slug: "body-weight-analyzer",
    name: "Smart Body Weight Composition Analyzer",
    description: "USB Charger Digital Weight Machine with Bluetooth. Tracks weight, body fat, BMI, and more. Blue LED display.",
    price: 35000,
    priceDisplay: "35,000 RWF",
    category: "Fitness",
    image: "/products/product-29.jpg",
    inStock: true,
  },
  {
    id: 30,
    slug: "waterproof-phone-case",
    name: "Waterproof Phone Case",
    description: "Universal waterproof phone case. Protects your phone from water, dust, and dirt. Clear screen access.",
    price: 7000,
    priceDisplay: "7,000 RWF",
    category: "Accessories",
    image: "/products/product-30.jpg",
    inStock: true,
  },
  {
    id: 31,
    slug: "laptop-stand-wooden",
    name: "Portable Foldable Laptop Stand Desk",
    description: "Multi Function Laptop Stand Bed Desk. Foldable wooden lap table tray. Works on bed, sofa, or floor.",
    price: 30000,
    priceDisplay: "30,000 RWF",
    category: "Office",
    image: "/products/product-31.jpg",
    inStock: true,
  },
  {
    id: 32,
    slug: "roller-sunshade",
    name: "Roller Sunshade for Car Window",
    description: "Car window roller sunshade, size 58×125cm. Protects interior from UV rays and heat.",
    price: 20000,
    priceDisplay: "20,000 RWF",
    category: "Accessories",
    image: "/products/product-32.jpg",
    inStock: true,
  },
  {
    id: 33,
    slug: "rain-coat-budget",
    name: "Rain Coat Budget",
    description: "Affordable quality rain coat. Available in multiple colors. Perfect protection during rainy season.",
    price: 12000,
    priceDisplay: "12,000 RWF",
    category: "Clothing",
    image: "/products/product-33.jpg",
    inStock: true,
  },
];

export const categories = [
  "All",
  "Kitchen",
  "Bathroom",
  "Home",
  "Fitness",
  "Office",
  "Garden",
  "Clothing",
  "Accessories",
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "All") return products;
  return products.filter((p) => p.category === category);
}

export function numericId(id: number | string): number {
  if (typeof id === "number") return id;
  let h = 0;
  for (let i = 0; i < id.length; i++) h = (Math.imul(h, 31) + id.charCodeAt(i)) | 0;
  return Math.abs(h) || 1;
}
